In [2]:
'''Numpy:stands for numerical python.It is a python library used for working with arrays.It also provides functions for working in domain of linear algebra and matrices(2-d array).
Efficiently handle multi-dimensional array.'''
#importing library
import numpy as np

creating arrays

In [3]:
#1.from list or tuple using np.array()
lists=[1,23,4,5]#mutable-update the values
print("creating array from list:")
a=np.array(lists)#1-d array
print(a)
b=np.array([[1,2],[3,4]])#2-d
print(b)
#tuple---()
print("creating array from tuple:")
tuples=(1,2,3,4)#immutable--can't update the value
c=np.array(tuples)
print(c)
d=np.array([(1,2),(3,4)])
print(d)


creating array from list:
[ 1 23  4  5]
[[1 2]
 [3 4]]
creating array from tuple:
[1 2 3 4]
[[1 2]
 [3 4]]


In [4]:
#np.zeros()---array of all zeros
np.zeros(6)
np.zeros((2,2))#2x3 matrix of all zeros

array([[0., 0.],
       [0., 0.]])

In [5]:
np.ones(5)
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
#np.full()
np.full((2,3),6)

array([[7, 7, 7],
       [7, 7, 7]])

In [7]:
#np.arrange similar to range() in python
np.arange(0,10,2)
np.arange(5)

array([0, 1, 2, 3, 4])

In [8]:
np.random.rand(16,16)#2x3 values[0,1]

array([[0.8094241 , 0.98437313, 0.72429664, 0.45370876, 0.10840801,
        0.30666284, 0.85876575, 0.43114541],
       [0.35067345, 0.70836618, 0.10339207, 0.30140265, 0.61515676,
        0.4989216 , 0.64624213, 0.65228896],
       [0.97532764, 0.47090619, 0.10274119, 0.05372495, 0.56492895,
        0.08354584, 0.56659491, 0.72333523],
       [0.9711276 , 0.76286157, 0.34742343, 0.36108661, 0.75105495,
        0.83303914, 0.16598117, 0.63852001],
       [0.04694334, 0.96559199, 0.38953128, 0.10781338, 0.84471477,
        0.97210236, 0.14887561, 0.87103556],
       [0.03745928, 0.15065952, 0.34579585, 0.36912387, 0.80549743,
        0.78624202, 0.91975773, 0.43650005],
       [0.61572851, 0.05700442, 0.24552348, 0.8843484 , 0.14519296,
        0.57453524, 0.40504118, 0.00974938],
       [0.22255805, 0.45943757, 0.99107585, 0.94709863, 0.99745115,
        0.38795709, 0.57636456, 0.74339503]])

**Properties of numpy**

In [9]:
#properties: which tells us everything about the structure,shape,size and type of array
arr=np.array([[10,20,30],[40,50,60]])
print(arr)
#1. ndim--number of dimensions
print(arr.ndim)
#2.shape--rows and columns in the form tuple
print(arr.shape)
#3.size--total number of values or elements
print(arr.size)
#4.dtype---data type of elements or values
print(arr.dtype)
#5.itemsize--size in bytes
print(arr.itemsize)
#6. nbytes--total size in bytes
print(arr.nbytes)#6x8
#7.T--transpose of the array
print(arr.T)

[[10 20 30]
 [40 50 60]]
2
(2, 3)
6
int64
8
48
[[10 40]
 [20 50]
 [30 60]]


**Indexing and slicing**

In [10]:
a=np.array([10,20,30])
print(a[0])#positive indexing
print(a[-1])#negative indexing
b=np.array([[1,2,3],[4,5,6]])
print(b[0,1])
print(b[1,0])#4

10
30
2
4


In [11]:
#slicing --accessing subset
a=np.array([10,20,30,40,50,60])
print(a[1:4])
print(a[:3])
print(a[::3])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b[1:3,0:2])
print("****")
print(b[:,0])#all rows , column 0
print(b[2,:])#row1

[20 30 40]
[10 20 30]
[10 40]
[[4 5]
 [7 8]]
****
[1 4 7]
[7 8 9]


**Arithmetic operations**

In [12]:
a=np.array([10,20,30])
b=np.array([40,50,60])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a-5)
print(a<b)

[50 70 90]
[-30 -30 -30]
[ 400 1000 1800]
[0.25 0.4  0.5 ]
[ 5 15 25]
[ True  True  True]


**Aggregate Functions**

In [13]:
#aggregate functions compute a single value from an array.
from scipy import stats
agg=np.array([[1,2,3],[4,5,6]])
print(agg.sum())
print(agg.min())
print(agg.max())
print(agg.mean())
print(agg.std())#standard deviation
print(agg.var())#variance
medain_value=np.median(agg)
print(medain_value)
mode_array=np.array([1,2,2,3,4,4,4,5,5,5])
mode_result=stats.mode(mode_array)
print(mode_result)

21
1
6
3.5
1.707825127659933
2.9166666666666665
3.5
ModeResult(mode=np.int64(4), count=np.int64(3))


**Matrix operations**

In [14]:
m1=np.array([[1,2],[3,4]])
m2=np.array([[5,6],[7,8]])
print(np.dot(m1,m2))#matrix multiplication
print(m1.T)

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


**Broadcasting**

In [15]:
#automatic expansion of smaller array to match with larger shape(array)
b1=np.array([[1,2,3],[4,5,6]])#2-d
b2=np.array([1,0,1])#1-d{1,0,1}

print(b1+b2)

[[2 2 4]
 [5 5 7]]


**Reshaping array**

In [16]:
a=np.array([1,2,3,4,5,6])#1-d
b=a.reshape((3,2))#3-rows,2-columns
print(b)
a1=np.array([10,20,30,40,50,60])#1-d
b1=a1.reshape((-1,2))
print(b1)


[[1 2]
 [3 4]
 [5 6]]
[[10 20]
 [30 40]
 [50 60]]


**flattening an array**

In [17]:
a=np.array([[1,2],[3,4]])#2-d
b=a.flatten()
print(b)

[1 2 3 4]


**Stacking**

In [21]:
#stacking:combing multiple arrays into single array(combining the arrays)
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
#np.vstack()-->row-wise
v=np.vstack((a,b))
print(v)
#np.hstack()-->column-wise
h=np.hstack((a,b))
print(h)
#np.stack
c=np.stack((a,b),axis=0)#row-wise
print(c)
d=np.stack((a,b),axis=1)#column-wise
print(d)


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


**Splitting arrays**

In [31]:
#splitting arrays:breaking a single array into smaller ones
x=np.array([[1,2,3,4,5,6]])
#np.hsplit()-->column-wise
hs=np.hsplit(x,3)
print(hs)
#np.vsplit()-->row-wsie
y=np.array([[1,2,3],[4,5,6]])
vs=np.vsplit(y,2) # Splitting into 2 sections along the row axis
print(vs)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
